name: Build

on: [ "push", "pull_request" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven Install
        run: mvn clean package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
